version: "3"
services:
  bananapp-spring:
    container_name: bananapp-spring
    image: bananapp-spring:latest
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/wrojees09?useUnicode=true&characterEncoding=utf8&useSSL=false
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /home/kuba/Desktop/projects/bananapp-react/target/classes/public/auth:/home/kuba/Desktop/projects/bananapp-react/target/classes/public/auth

  bananapp-react:
    container_name: bananapp-react
    image: bananapp-react:latest
    volumes:
      - '/node_modules'
    ports:
      - "8083:8083"
    depends_on:
      - bananapp-spring
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  bananapp-264116:
    container_name: bananapp-264116
    image: bananapp-264116:latest
    ports:
      - "8082:8082"
    volumes:
      - /home/kuba/Desktop/projects/bananapp-react/target/classes/public/auth:/home/kuba/Desktop/projects/bananapp-react/target/classes/public/auth

  db:
    image: mysql:5.7
    container_name: db
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --skip-character-set-client-handshake
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wrojees09
    volumes:
      - /home/db:/var/lib/mysql

  adminer:
   image: adminer
   ports:
      - "5000:8080"
